### ISSUE TITLE
long poll report + update UI (forever?)

### ISSUE THREAD

**Issue by pkarl** [scorebuilders/sbuilder-webapp#3]
The discuss page will receive more/better results as folks submit them. Here's the play:
- install a long-polling device in this view to query `/api/report/[sessionId]` for JSON blobs of reports
- update the user on how many people are reporting results (and decide whether this is determined on the client side or server side + added to payload)
  - ex: "number of users reporting: 6"
- pipe results into UI that shows both averages for self/team/company scores but also matches individual scores to comments

**Comment by wolfgangcodes** [comment]
Or websockets?

**Comment by pkarl** [comment]
whatever's simpler, :ship: !

**Comment by pkarl** [comment]
I'm tinkering this AM w/a PR. Implementing short polling b/c we don't have a dep yet for INSTANT server-->client notification.
